name: Integration Test
on:
  schedule:
    - cron:  '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: jacobtomlinson/python-container-action@master

      - name: Check outputs
        run: |
          python main.py
          git add .
          git commit -m "automated commit"
          git push
